### ISSUE TITLE
Jenkins builds clutter up machines

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1058] opened 2021-03-26 12:20 UTC
## Describe the bug
Different installers that Jenkins builds doesn't get removed from machines and sooner or later machines run out of space.

## Expected behavior
Before run of a new build remove outdated builds?

**Comment by mssalvatore** [comment] 2021-06-01 09:04
Duplicate of https://github.com/guardicore/monkey/issues/1134

**Closed by mssalvatore** 2021-06-01 09:04 UTC
Labels: Bug, DevOps, Expert, Priority: High
