### ISSUE TITLE
Update RDP to use aardwolf v0.2.8

### ISSUE THREAD

**Issue by cakekoa** [guardicore/monkey#3780] opened 2023-10-10 20:32 UTC
Our [PR got merged into aardwolf](https://github.com/skelsec/aardwolf/pull/19), so now we can switch from using my fork to the official aardwolf release

**Comment by shreyamalviya** [comment] 2023-10-11 05:42
Duplicate of #3712

**Closed by shreyamalviya** 2023-10-11 05:42 UTC
Labels: Feature
