### ISSUE TITLE
Run the infection-monkey with a configuration file doesn't work as expected

### ISSUE THREAD

**Issue by noctx** [guardicore/monkey#244] opened 2019-01-07 16:48 UTC
**Describe the bug**
Running the infection-monkey with a configuration file doesn't work as expected.
Version used: Latest infection-monkey release

**To Reproduce**
1. Run an infection monkey with the following command: monkey-linux-64 m0nk3y -c ./monkey.conf
2. The logs show that the specified monkey.conf is successfuly loaded by the infection monkey 
3. After the infection monkey contacted the monkey-island, the infection monkey's configuration is overrided by the monkey-island's config file.

**Expected behavior**
The infection monkey should keep the configuration file values loaded at execution time.

**Screenshots**
Config file loading success
![success_loading](https://user-images.githubusercontent.com/8222461/50780787-223efa80-12a4-11e9-8dfe-2a5d340190cb.png)

Config file overrided by monkey island
![server_override](https://user-images.githubusercontent.com/8222461/50780803-2cf98f80-12a4-11e9-9256-9a1a2ea921b1.png)

**Comment by dberuben** [comment] 2019-01-07 16:50
👍

**Comment by danielguardicore** [comment] 2019-01-21 09:40
Hey,

What would you suggest as proper behavior? To ignore the configuration given by the Island during the entire run?

**Comment by noctx** [comment] 2019-01-21 11:06
Hi,

At first sight I think that it should be the correct behavior, yes. Otherwise, what is this feature designed for ?

Thanks.

**Comment by danielguardicore** [comment] 2019-01-29 07:41
Agree, though that means it'll be hard (for us in code) to kill the monkey remotely, will need a seperate heartbeat channel. But you're correct.

**Comment by VakarisZ** [comment] 2019-12-13 15:30
Can't we just ignore everything from server config if user passed custom config except 'alive'?

**Comment by VakarisZ** [comment] 2021-01-20 15:34
@mssalvatore Looks like people actually used this feature.
To do this properly we probably should add help for arguments, add a mechanism to automatically update default config example. This could solve an issue of running different configs for different machines.

**Comment by mssalvatore** [comment] 2021-01-20 16:46
It sounds like the actual desire is to have per-monkey or per-system configs. A better workflow might be:

1) Create a general config in Monkey Island
2) Create a per-system config in Monkey Island (new feature)
3) Start the monkey on the target system (monkey calls home to the island)
4) Island configures the monkey with the specific config

Using this approach, users can configure their breach & attack simulations from a central location. 

I think this is still an enhancement and not a bug.

> At first sight I think that it should be the correct behavior, yes. Otherwise, what is this feature designed for ?

As far as I can tell, this feature is a vestigial remnant of a time before Monkey Island. The use case is valid, but I think we can support it in a better way than by passing configs to the monkey on the command line.

**Comment by mssalvatore** [comment] 2022-05-24 22:23
It's been some time since this issue was created with little activity. We're planning some more advanced features that would better support this use case. Closing this as won't fix.

**Closed by mssalvatore** 2022-05-24 22:23 UTC
Labels: Bug, Enhancement, Impact: Medium, Complexity: Medium
