### ISSUE TITLE
Clear Infection Map button. 

### ISSUE THREAD

**Issue by Piesa** [guardicore/monkey#1816] opened 2022-03-25 10:38 UTC
I'm trying to arrange my servers in different ways and then run Infection monkey. The issue is that Infection Map is stored between runs and afaik there is no possibility to just clear it to have new one each run.

Great solution for that would be just a button clearing the Infection map. 

Not sure what alternatives could be here, maybe just listing in documentation where exactly map is stored, so it could be deleted manually. 

Cheers!

**Comment by mssalvatore** [comment] 2022-03-25 11:21
Duplicate of https://github.com/guardicore/monkey/issues/957

**Comment by VakarisZ** [comment] 2022-04-14 13:45
Closed because it's duplicate of #957

**Closed by VakarisZ** 2022-04-14 13:45 UTC
Labels: Duplicate, Feature
