### ISSUE TITLE
MSI installer contains unnecessary source code

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#912] opened 2021-01-04 15:16 UTC
## Describe the bug
Upon island install on windows, source code is extracted to install directory, which is unnecessary. 

## To Reproduce
1. Download msi installer and install island
2. Open island installation folder. It contains source code which can be deleted.

## Expected behavior
Install dir should contain only necessary files

## Machine version (please complete the following information):
 - OS: Windows

**Comment by mssalvatore** [comment] 2022-10-31 16:41
Duplicate of #1328

**Closed by mssalvatore** 2022-10-31 16:41 UTC
Labels: Bug, Duplicate, Complexity: Medium
