### ISSUE TITLE
No Docker download/deb for 1.9.0

### ISSUE THREAD

**Issue by rpedrica** [guardicore/monkey#777] opened 2020-08-11 06:41 UTC
## Describe the bug
The current Dockerfile includes the following statement to download the deb package as part of the container build process:

ADD https://github.com/guardicore/monkey/releases/download/${RELEASE}/infection_monkey_deb.${RELEASE}.tgz .

This path/file does not exist and therefore the docker pull/build/run fails.

## To Reproduce
1. Edit the Dockerfile to specify version:
ARG RELEASE=1.9.0
2. docker-compose up
3. See error below

`docker-compose up
Building monkey
Step 1/11 : FROM debian:stretch-slim
 ---> 8ff748cdd6b1
Step 2/11 : LABEL MAINTAINER="theonlydoo <theonlydoo@gmail.com>"
 ---> Using cache
 ---> 93f19c6ec471
Step 3/11 : ARG RELEASE=1.9.0
 ---> Using cache
 ---> 5b97a0c24629
Step 4/11 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 48f1fd2996d1
Step 5/11 : EXPOSE 5000
 ---> Using cache
 ---> bd26e7575025
Step 6/11 : WORKDIR /app
 ---> Using cache
 ---> 11a3eef86708
Step 7/11 : ADD https://github.com/guardicore/monkey/releases/download/${RELEASE}/infection_monkey_deb.${RELEASE}.tgz .
ERROR: Service 'monkey' failed to build: ADD failed: failed to GET https://github.com/guardicore/monkey/releases/download/1.9.0/infection_monkey_deb.1.9.0.tgz with status 404 Not Found: <!DOCTYPE html>
`

## Expected behavior
The 'docker-compose' action should download the remote file and build the container/start it.

## Machine version (please complete the following information):
 - OS: Linux Slackware 15

**Comment by itaymmguardicore** [comment] 2020-08-11 16:44
Hi, we actually need to update the docker-compose script to deploy using the code, instead of the precompiled deb option.

Until we get to that, you can download the .deb option from the [Infection Monkey](https://infectionmonkey.com/) site and plug the link you'll get there. However, we do offer a Docker option there as well, so you could just use that.

**Comment by itaymmguardicore** [comment] 2020-08-11 16:44
Closing because duplicate of #641

**Closed by itaymmguardicore** 2020-08-11 16:44 UTC
Labels: Bug, Duplicate

**Comment by rpedrica** [comment] 2020-08-11 18:13
Thanks @itaymmguardicore however your download link email form is not working. See screenshot.

![infectionmonkey](https://user-images.githubusercontent.com/1016286/89933126-e81ba480-dc0e-11ea-99ba-926ec3a57e85.png)

That iframe seems to point to go.guardicore.com which doesn't exist as a dns record. Any other options for downloading?

**Comment by rpedrica** [comment] 2020-08-12 07:20
Apologies the above was a dns error on my side.
