### ISSUE TITLE
PermissionError when running local monkey

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#3578] opened 2023-08-10 12:21 UTC
## Describe the bug
When we try to run the agent from the island using Run Local Monkey service on Windows sometimes we get PermissionError that we can't access the agent.

This is a bit racey due to the fact that the agent can still be running on the machine.
The issue is produced by this lines: https://github.com/guardicore/monkey/blob/e587368339a9c23a9045f0ff9eeece15e7f03a7b/monkey/monkey_island/cc/services/run_local_monkey.py#L61-L68

What was tried is using `common.utils.file_utils.open_securely_permissioned_file` which doesn't create the agent if it is already existing.

## To Reproduce
1. Run depth_3 BB tests couple of time
1. You should see error.

## Expected behavior
Two things shouldn't happen: the agent should be stopped and not used by a process and the agent should be created on the machine regardless if it is existing or not.

## Screenshots
Error message now.
![image](https://github.com/guardicore/monkey/assets/15820737/9290feff-f2b3-4199-8c3f-736caf8b775e)

The check with `common.utils.file_utils.open_securely_permissioned_file`
![image](https://github.com/guardicore/monkey/assets/15820737/645238f2-35a5-48ba-9798-1c51086afb23)

## Machine version (please complete the following information):
 - OS: Windows

**Comment by mssalvatore** [comment] 2023-08-10 12:45
This is probably caused by #3543

**Comment by mssalvatore** [comment] 2023-08-16 18:47
I think this is resolved by #3557 and #3543. @ilija-lazoroski Please confirm.

**Comment by cakekoa** [comment] 2023-08-17 12:06
Confirmed, this is resolved by #3543

**Closed by cakekoa** 2023-08-17 12:06 UTC
Labels: Bug
